name: pr-linter

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened

permissions:
  contents: read
  pull-requests: write
  issues: read

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Lint pull request title
        uses: jef/conventional-commits-pr-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
